/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.AccountDirectory;

/**
 *
 * @author aadilkarim
 */
public class AMWorkAreaJP extends javax.swing.JPanel {
    JPanel userProcCont;
    AccountDirectory accountDirectory;
    
    /**
     * Creates new form AMWorkAreaJP
     */
    public AMWorkAreaJP(JPanel container, AccountDirectory directory) {
        initComponents();
        
        userProcCont = container;
        accountDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAcc = new javax.swing.JButton();
        btnManageAcc = new javax.swing.JButton();

        btnCreateAcc.setText("Create Account");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        btnManageAcc.setText("Manage Account");
        btnManageAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageAcc)
                    .addComponent(btnCreateAcc))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateAcc, btnManageAcc});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCreateAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageAcc)
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        CreateAcc panel = new CreateAcc (userProcCont, accountDirectory);
        userProcCont.add("CreateAcc",panel);
        
        CardLayout layout = (CardLayout) userProcCont.getLayout();
        layout.next(userProcCont);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnManageAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccActionPerformed
        ManageAcc panel = new ManageAcc (userProcCont, accountDirectory);
        userProcCont.add("ManageAcc",panel);
        
        CardLayout layout = (CardLayout) userProcCont.getLayout();
        layout.next(userProcCont);
    }//GEN-LAST:event_btnManageAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnManageAcc;
    // End of variables declaration//GEN-END:variables
}
